CREATE TABLE IF NOT EXISTS users(p_userID INTEGER PRIMARY KEY AUTOINCREMENT, userName VARCHAR(100) NOT NULL, password VARCHAR(100) NOT NULL);		
				
CREATE TABLE IF NOT EXISTS chats(p_chatID INTEGER PRIMARY KEY AUTOINCREMENT, f_user1 VARCHAR(100) NOT NULL, f_user2 VARCHAR(100) NOT NULL, FOREIGN KEY(f_user1) REFERENCES user(p_userID), FOREIGN KEY(f_user2) REFERENCES user(p_userID));
				
CREATE TABLE IF NOT EXISTS messages(p_messageID INTEGER PRIMARY KEY AUTOINCREMENT, text VARCHAR, date DATETIME NOT NULL, f_sentBy VARCHAR(100) NOT NULL, f_chatID INTEGER NOT NULL, FOREIGN KEY(f_chatID) REFERENCES chat(p_chatID), FOREIGN KEY(f_sentBy) REFERENCES user(p_userID));